schema = 3

[mod]
  [mod."github.com/fsnotify/fsnotify"]
    version = "v1.4.9"
    hash = "sha256-HZBMhbFqcZM9oxSbWqISzEE7GF7JZpco5tyta6c4OcQ="
  [mod."github.com/sigmonsays/go-logging"]
    version = "v0.0.0-20170415192813-93f4813d2694"
    hash = "sha256-CsxSAqDZ8gaAmdsTRp9C2U2f8PKrIBNdOt8sfAAfA6M="
  [mod."github.com/whilp/git-urls"]
    version = "v1.0.0"
    hash = "sha256-ozB2hEpZ1R8Ykw5Poj788R+cxdhg4SHKfLP0qDAbg1U="
  [mod."golang.org/x/sys"]
    version = "v0.0.0-20191005200804-aed5e4c7ecf9"
    hash = "sha256-Rhfb5W7UmO3cvG34ei4pS1nFCtUibqsF2ByQRYRTOJA="
  [mod."gopkg.in/check.v1"]
    version = "v0.0.0-20161208181325-20d25e280405"
    hash = "sha256-1w5mgYaZUC52uzDnpXXVqle/9AVkH4WePSrQFOVANUw="
  [mod."gopkg.in/yaml.v2"]
    version = "v2.4.0"
    hash = "sha256-uVEGglIedjOIGZzHW4YwN1VoRSTK8o0eGZqzd+TNdd0="
