# Docs https://github.com/marketplace/actions/go-release-binaries
name: release go binaries
on:
   push:
     branches: [ master ]

jobs:
  release-linux-amd64:
    name: release linux/amd64
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64]
    steps:
    - uses: actions/checkout@v2
    - uses: wangyoucao577/go-release-action@v1.14
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        project_path: ./cmd/git-caddy
        binary_name: git-caddy
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        overwrite: true
        asset_name: git-caddy-latest-${{ matrix.goos }}-${{ matrix.goarch }}
