name: goreleaser

on:
  # push:
  #   tags: [ 'v*' ]
  push:
    branches:
      - dev
      - go-releaser*

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Release Version
        id: version
        run: |
          export RELEASE_VERSION=v0.1.${{ github.run_number }}
          export PACKAGE_VERSION=$(echo $RELEASE_VERSION | sed 's/v//')
          echo "RELEASE_VERSION=$RELEASE_VERSION" >> $GITHUB_ENV
          echo "release_version=$RELEASE_VERSION" >> $GITHUB_OUTPUT
          echo "package_version=$PACKAGE_VERSION" >> $GITHUB_OUTPUT

      - name: create tag
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
          GITHUB_REPOSITORY: sigmonsays/git-caddy
        shell: bash {0}
        run: |
          curl \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer $GH_PAT" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              -s \
              https://api.github.com/repos/$GITHUB_REPOSITORY/git/ref/tags/$RELEASE_VERSION | jq -r .message | grep -i "not found" > /dev/null
          if [ $? -eq 0 ]; then
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git tag -a $RELEASE_VERSION -m $RELEASE_VERSION
            git push origin $RELEASE_VERSION
          else
            echo "tag already exists, not creating a new tag"
          fi

      - name: Set up Go
        uses: actions/setup-go@v4


      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
